### ISSUE TITLE
frederative style is not dimension-less

### ISSUE THREAD

**Issue by camilleroux** [camilleroux/fxhash-bridge#58]
Hi @frederative 

Your style is not dimension-less currently. Here is an exemple
![image](https://user-images.githubusercontent.com/25977/154822755-45280465-20b2-43fc-aabc-80e92a3d4a44.png)
![image](https://user-images.githubusercontent.com/25977/154822759-3ad21f0c-b82c-49a2-a97a-1a7862265dd3.png)
![image](https://user-images.githubusercontent.com/25977/154822765-4aa32dd1-81a4-4cb8-9df3-f888b709fd29.png)

**Comment by frederative** [comment]
Oops, you know I looked and looked and though it was fine.  That moon though...

I pushed a fix.  Does it work OK for you now?  I *think* it was just the moon sizing not being tied to the canvas width that was the issue...it looks OK to me now but I'm concerned I'm missing something else obvious.

**Comment by camilleroux** [comment]
It's better. But it looks like it's still not responsive.
![image](https://user-images.githubusercontent.com/25977/154841962-1f3afdd9-79be-4fc3-924d-2b37d9e17d81.png)
![image](https://user-images.githubusercontent.com/25977/154841965-6cadac9b-1802-4f12-8a32-d829c9ebe2c6.png)

**Comment by frederative** [comment]
Ok, second fixes made with a scaling factor (for some reason I hadn't thought I needed it for what i was doing).  Good reason to actually use the browser dev tools rather than dragging the window back and forth ... noticed what you're seeing when I went into phone preview mode.

One other point though, the dithering might do wonky things with smaller sizes just purely based on the pixel array.  As far as I can tell though, everything should be scaling now properly though.
